#!/usr/bin/env bash
# One-shot setup for a fresh clone of this repo (e.g. a cloud session with
# no access to the original machine's local folders). Installs the package,
# points the CSV/strategy env vars at what's actually bundled in the repo,
# and verifies the MCP server imports cleanly.
#
# Usage:
#   bash scripts/setup.sh              # base install only
#   bash scripts/setup.sh --risk       # + QuantLib (calculate_option_greeks)
#   bash scripts/setup.sh --ml         # + LightGBM (run_alpha_factor_analysis)
#   bash scripts/setup.sh --rl         # + Gymnasium (train_rl_trading_agent, Q-learning path)
#   bash scripts/setup.sh --rl-full    # + Gymnasium + stable-baselines3 (adds PPO; large download)
#   bash scripts/setup.sh --all        # all of the above
#
# Safe to re-run — every step is idempotent.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

EXTRAS=()
for arg in "$@"; do
    case "$arg" in
        --risk) EXTRAS+=("risk") ;;
        --ml) EXTRAS+=("ml") ;;
        --rl) EXTRAS+=("rl") ;;
        --rl-full) EXTRAS+=("rl-full") ;;
        --all) EXTRAS+=("risk" "ml" "rl-full") ;;
        *) echo "unknown flag: $arg" >&2; exit 1 ;;
    esac
done

echo "==> Installing base package (editable) from $REPO_ROOT"
python -m pip install --upgrade pip -q
if [ ${#EXTRAS[@]} -eq 0 ]; then
    python -m pip install -e . -q
else
    # Join extras into pip's "[a,b,c]" syntax, deduplicated.
    joined=$(printf "%s," "${EXTRAS[@]}" | sed 's/,$//' | tr ',' '\n' | sort -u | paste -sd, -)
    echo "    with optional extras: $joined"
    python -m pip install -e ".[$joined]" -q
fi

echo "==> Pointing data/strategy env vars at the repo's bundled copies"
export TV_MCP_CSV_DATA_DIR="$REPO_ROOT/data"
export TV_MCP_STRATEGIES_DIR="$REPO_ROOT/local_data/strategies"
export TV_MCP_PINE_STRATEGIES_DIR="$REPO_ROOT/local_data/pine_strategies"

ENV_FILE="$REPO_ROOT/.env.local"
cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup.sh — source this file (or let your MCP client
# load it) so the server finds the repo's bundled CSV/strategy data.
export TV_MCP_CSV_DATA_DIR="$TV_MCP_CSV_DATA_DIR"
export TV_MCP_STRATEGIES_DIR="$TV_MCP_STRATEGIES_DIR"
export TV_MCP_PINE_STRATEGIES_DIR="$TV_MCP_PINE_STRATEGIES_DIR"
EOF
echo "    wrote $ENV_FILE — 'source scripts/setup.sh's env' or 'source .env.local' in future shells"

if [ ! -f "$TV_MCP_CSV_DATA_DIR/XAUUSD_M1.csv" ]; then
    echo "==> NOTE: XAUUSD_M1.csv is not in the repo (120MB, over GitHub's 100MB file limit)."
    echo "    Extract XAUUSD_csv_data.zip into $TV_MCP_CSV_DATA_DIR if you need M1-resolution backtests."
fi

echo "==> Verifying the server imports and registers tools"
python -c "
from tradingview_mcp import server
tools = server.mcp._tool_manager.list_tools()
print(f'    OK — {len(tools)} tools registered')
"

echo "==> Done. Run the server with: tradingview-mcp"
echo "    (or: python -m tradingview_mcp.server)"
